#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "cli.h"

static void output_bash(const char *alias_name)
{
    const char *name = alias_name ? alias_name : "crap";

    printf("# Generated by thecrap init - add this to ~/.bashrc\n");
    printf("%s() {\n", name);
    printf("    local previous_cmd\n");
    printf("    previous_cmd=\"$(fc -ln -1)\"\n");
    printf("    local fixed_cmd\n");
    printf("    fixed_cmd=\"$(CRP_SELECT=1 thecrap fix \"$previous_cmd\")\"\n");
    printf("    if [ $? -eq 0 ] && [ -n \"$fixed_cmd\" ]; then\n");
    printf("        eval \"$fixed_cmd\"\n");
    printf("    fi\n");
    printf("}\n");
    printf("\n");
    printf("complete -F %s %s\n", name, name);
}

static void output_zsh(const char *alias_name)
{
    const char *name = alias_name ? alias_name : "crap";

    printf("# Generated by thecrap init - add this to ~/.zshrc\n");
    printf("%s() {\n", name);
    printf("    local previous_cmd\n");
    printf("    previous_cmd=\"$(fc -ln -1)\"\n");
    printf("    local fixed_cmd\n");
    printf("    fixed_cmd=\"$(CRP_SELECT=1 thecrap fix \"$previous_cmd\")\"\n");
    printf("    if [ $? -eq 0 ] && [ -n \"$fixed_cmd\" ]; then\n");
    printf("        eval \"$fixed_cmd\"\n");
    printf("    fi\n");
    printf("}\n");
    printf("\n");
    printf("compdef %s %s\n", name, name);
}

static void output_fish(const char *alias_name)
{
    const char *name = alias_name ? alias_name : "crap";

    printf("# Generated by thecrap init - add this to ~/.config/fish/config.fish\n");
    printf("function %s\n", name);
    printf("    set -l previous_cmd $history[1]\n");
    printf("    set -l fixed_cmd (CRP_SELECT=1 thecrap fix \"$previous_cmd\")\n");
    printf("    if test $status -eq 0 -a -n \"$fixed_cmd\"\n");
    printf("        eval \"$fixed_cmd\"\n");
    printf("    end\n");
    printf("end\n");
}

int crap_init(crap_init_cmd *init)
{
    switch (init->shell) {
    case CRP_SHELL_BASH:
        output_bash(init->alias_name);
        break;

    case CRP_SHELL_ZSH:
        output_zsh(init->alias_name);
        break;

    case CRP_SHELL_FISH:
        output_fish(init->alias_name);
        break;

    case CRP_SHELL_PWSH:
        printf("# Generated by thecrap init - add this to $PROFILE\n");
        printf("# PowerShell support coming soon\n");
        break;

    default:
        fprintf(stderr, "error: unsupported shell\n");
        return -1;
    }

    return 0;
}
